events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # Rota para o Frontend (Vite)
        location / {
            proxy_pass http://frontend:5173;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

        # Rota para a API (Backend)
        # O frontend chamará /api/login, e o nginx manda para o backend
        location /api/ {
            rewrite ^/api/(.*) /$1 break;
            proxy_pass http://api_backend:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Opcional: Rota para o InfluxDB (se precisar ver o painel dele)
        location /influx/ {
            proxy_pass http://influxdb:8086/;
        }
    }
}